### ISSUE TITLE
Use this bundle in my projet ?

### ISSUE THREAD

**Issue by picks44** [gikoluo/PinyinBundle#1]
Hello,

I need to convert chinese characters into Pinyin in one of my Symfony projects.
Can I use this bundle ?

**Comment by gikoluo** [comment]
sure, and nolicence needed.

Original Message
Sender:VinZnotifications@github.com
Recipient:gikoluo/PinyinBundlePinyinBundle@noreply.github.com
Date:Friday, Mar 11, 2016 18:51
Subject:[PinyinBundle] Use this bundle in my projet ? (#1)

Hello,
I need to convert chinese characters into Pinyin in one of my Symfony projects.
 Can I use this bundle ?
